spring.application.name=finance-dashboard-backend
server.port=8080

spring.datasource.url=jdbc:sqlite:finance-dashboard.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

app.jwt.secret=ZmluYW5jZS1kYXNoYm9hcmQtc3lzdGVtLXN1cGVyLXNlY3JldC1rZXktZm9yLWFzc2Vzc21lbnQ=
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=604800000
app.auth.password-reset-expiration-ms=1800000
